#!/usr/bin/env python3
'''
Declassed Plausible Deniabity Toolkit

Unmount volume.

Example:

    dpdt_unmount /mnt/my-hidden-volume

Copyright 2022 AXY axy@declassed.art
License: BSD, see LICENSE for details.
'''

import sys

from dpdt_base import Invoke

directory = sys.argv[1]

invoke = Invoke()
invoke.locrypt_unmount(directory)
